<a href="https://colab.research.google.com/github/muhammadsajad/PyTorch-Learning/blob/main/dataset_and_dataloader_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import make_classification
import torch

In [3]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [4]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
X.shape

(10, 2)

In [6]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [7]:
y.shape

(10,)

In [8]:
# Convert the data to PyTorch tensors
X=torch.tensor(X,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)

In [9]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [10]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [11]:
from torch.utils.data import Dataset, DataLoader

In [24]:
class CustomDataset(Dataset):

  def __init__(self,features,labels):

    self.features=features
    self.labels=labels

  def __len__(self):

      return self.features.shape[0]

  def __getitem__(self,index):

      return self.features[index], self.labels[index]

In [25]:
dataset=CustomDataset(X,y)

In [26]:
len(dataset)

10

In [27]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [33]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [34]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.7273, -1.1858],
        [ 1.8997,  0.8344]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-0.5872, -1.9717]])
tensor([0, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.7774,  1.5116]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.0683, -0.9701]])
tensor([0, 1])
--------------------------------------------------

In [35]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [37]:
df.shape

(569, 33)

In [38]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [39]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [40]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [41]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [42]:
X_train

array([[-1.3858191 , -1.27928914, -1.33350273, ..., -0.65132775,
         1.2007064 ,  0.32868694],
       [-1.35404581,  0.54552694, -1.34860396, ..., -1.18480829,
        -0.05927576, -0.05424243],
       [-0.21742837, -0.82074561, -0.22062555, ...,  0.84858977,
         0.96085813,  0.99401261],
       ...,
       [-0.94532569,  1.1327434 , -0.95890819, ..., -1.26211103,
         0.23196857, -0.43717181],
       [-0.44272992, -0.06976361, -0.41232735, ..., -0.34532502,
        -1.22892545, -0.68455096],
       [-0.76046288, -0.28265882, -0.76175316, ..., -0.91913743,
        -1.09342675, -0.43039429]])

In [43]:
y_train

520    B
416    B
81     B
184    M
285    B
      ..
315    B
164    M
549    B
355    B
304    B
Name: diagnosis, Length: 455, dtype: object

In [44]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [45]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [46]:
X_train_tensor.shape

torch.Size([455, 30])

In [47]:
y_train_tensor.shape

torch.Size([455])

In [48]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]

In [49]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [50]:
train_dataset[10]

(tensor([ 1.0362,  0.3209,  1.0760,  0.9196,  1.1127,  1.1746,  1.2054,  1.5018,
          0.5808, -0.1624,  1.5709,  0.3151,  1.3803,  1.3485,  0.7261,  1.3051,
          0.5911,  1.0410, -0.3472,  0.4325,  0.9096, -0.1194,  0.7910,  0.8030,
          0.4283,  0.5966,  0.3826,  0.5537, -0.6963, -0.3739]),
 tensor(1.))

In [51]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [52]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [53]:
learning_rate = 0.1
epochs = 25

In [54]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [55]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.17825843393802643
Epoch: 2, Loss: 0.14188848435878754
Epoch: 3, Loss: 0.1613084375858307
Epoch: 4, Loss: 0.0796811580657959
Epoch: 5, Loss: 0.031196925789117813
Epoch: 6, Loss: 0.16625244915485382
Epoch: 7, Loss: 0.033425889909267426
Epoch: 8, Loss: 0.09883054345846176
Epoch: 9, Loss: 0.092202328145504
Epoch: 10, Loss: 0.03501872345805168
Epoch: 11, Loss: 0.015445279888808727
Epoch: 12, Loss: 0.046397093683481216
Epoch: 13, Loss: 0.03493181988596916
Epoch: 14, Loss: 0.021376965567469597
Epoch: 15, Loss: 0.06164894253015518
Epoch: 16, Loss: 0.01428561843931675
Epoch: 17, Loss: 0.0630974993109703
Epoch: 18, Loss: 0.09452088177204132
Epoch: 19, Loss: 0.11248456686735153
Epoch: 20, Loss: 0.11979294568300247
Epoch: 21, Loss: 0.0068078963086009026
Epoch: 22, Loss: 0.014886300079524517
Epoch: 23, Loss: 0.005743615794926882
Epoch: 24, Loss: 0.03701243922114372
Epoch: 25, Loss: 0.07467420399188995

In [56]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9531